on:
  push:
    branches:
      - debug
  release:
    types: [ created ]


name: Build artifacts

jobs:
  upload-release:
    if: ${{ github.event_name == 'release' }}
    name: Upload nginx configuration artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
      - name: Generate artifacts
        run: |
          bash generate_artifact.sh
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@f589ce0779c7bef1faf175f7488c972eb47dc046
        env:
          GITHUB_TOKEN: ${{ github.token }}
        if: ${{ github.event_name == 'release' }}
      - name: Upload Full Node Release Asset
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./babylon-nginx-fullnode-conf.zip
          asset_name: babylon-nginx-fullnode-conf.zip
          asset_content_type: application/zip

  debug:
    name: Debug
    runs-on: ubuntu-latest
    environment: publish-dockerhub
    steps:
      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  docker:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    environment: publish-dockerhub
    steps:
      - name: Login to Dockerhub
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
      - name: Set Environment Variables
        run: |
          NGINX_IMG_TAGS=0.0.0-rc1
          echo "Image tag: $NGINX_IMG_TAGS"
          echo "NGINX_IMG_TAGS=$NGINX_IMG_TAGS" >> $GITHUB_ENV
      - name: Docker build and push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          file: ./Dockerfile.alpine
          push: true
          tags: ${{ env.NGINX_IMG_TAGS }}
