on:
  pull_request:
  release:
    types: [ created ]


name: Build artifacts

jobs:
   build-push-container-gcr:
    if: github.event_name == 'pull_request'
    name: GCR
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@main
    with:
      # image information
      image_registry: "eu.gcr.io"
      image_organization: "dev-container-repo"
      image_name: "babylon-nginx"
      tag: ${{ github.head_ref }}
      # build information
      restore_artifact: "false"
      context: "."
      dockerfile: "./Dockerfile.alpine"
      platforms: "linux/amd64"
      # optimizations
      cache_tag_suffix: "pr"
      enable_trivy: "true"
    secrets:
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
      service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}