on:
  push:
  pull_request:
  release:
    types: [ created ]


name: Build artifacts

jobs:
   build-push-container-gcr:
    name: GCR
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@fix/default-tag-type
    with:
      # image information
      image_registry: "eu.gcr.io"
      image_organization: "dev-container-repo"
      image_name: "babylon-nginx"
      tags: |
        type=sha,event=branch
        type=sha,event=pr
        type=semver,pattern={{version}}
      # build information
      restore_artifact: "false"
      context: "."
      dockerfile: "./Dockerfile.alpine"
      platforms: "linux/amd64"
      # optimizations
      cache_tag_suffix: "pr"
      enable_trivy: "true"
    secrets:
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
      service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}